// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gox

import (
	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int32                 `gorm:"column:id;type:int(11);primaryKey" json:"id"`
	CreateBy string                `gorm:"column:create_by;type:varchar(255)" json:"create_by"`
	CreateAt int32                 `gorm:"column:create_at;type:int(11)" json:"create_at"`
	UpdateBy string                `gorm:"column:update_by;type:varchar(255)" json:"update_by"`
	UpdateAt int32                 `gorm:"column:update_at;type:int(11)" json:"update_at"`
	IsDel    soft_delete.DeletedAt `gorm:"column:is_del;type:tinyint(4);softDelete:flag" json:"is_del"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
